import { supabaseAdmin } from "./supabase-admin.js";

const ALLOWED_CATEGORIES = [
  "restaurants",
  "cafes",
  "bakeries",
  "hotels",
  "gyms",
  "beauty_salons",
  "pharmacies",
  "supermarkets",
] as const;

type AgentTask = {
  id: number;
  task_type: string;
  category: string | null;
  city: string | null;
  government_rate: string | null;
};

type AgentStatus = "idle" | "processing" | "error";

type AgentState = {
  name: string;
  status: AgentStatus;
  lastHeartbeat: string;
  processedCount: number;
  errors: number;
};

const WAIT_MS = 1000;

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function isAllowedCategory(value: string | null): value is (typeof ALLOWED_CATEGORIES)[number] {
  return Boolean(value && ALLOWED_CATEGORIES.includes(value as (typeof ALLOWED_CATEGORIES)[number]));
}

function generateMockBusinesses(task: AgentTask, agentName: string) {
  if (!isAllowedCategory(task.category)) {
    return [];
  }

  const city = task.city ?? "unknown";
  return [1, 2, 3].map((n) => ({
    name: `${task.category}-${city}-${n}`,
    category: task.category,
    government_rate: task.government_rate,
    city,
    address: `${n} Main Street`,
    phone: `+964-000-000-000${n}`,
    website: `https://${task.category}-${city}-${n}.example.com`,
    description: `Generated by ${agentName}`,
    source_url: "https://example.com/source",
    verification_status: "verified",
    created_by_agent: agentName,
  }));
}

export class AgentSystem {
  private running = false;
  private managerTimer?: NodeJS.Timeout;
  private readonly agentStates: AgentState[];

  constructor(private readonly agentCount = 18) {
    this.agentStates = Array.from({ length: agentCount }, (_, index) => ({
      name: `agent_${index + 1}`,
      status: "idle",
      lastHeartbeat: new Date().toISOString(),
      processedCount: 0,
      errors: 0,
    }));
  }

  getStatus() {
    return {
      running: this.running,
      agents: this.agentStates,
    };
  }

  async start() {
    if (this.running) {
      return;
    }
    this.running = true;

    this.agentStates.forEach((agent) => {
      this.runAgentLoop(agent).catch((error) => {
        console.error(`Fatal loop error for ${agent.name}`, error);
      });
    });

    this.managerTimer = setInterval(() => {
      this.runManagerChecks().catch((error) => {
        console.error("Manager check failed", error);
      });
    }, 5000);
  }

  stop() {
    this.running = false;
    if (this.managerTimer) {
      clearInterval(this.managerTimer);
      this.managerTimer = undefined;
    }
  }

  private async runAgentLoop(agent: AgentState) {
    while (this.running) {
      agent.lastHeartbeat = new Date().toISOString();
      try {
        const task = await this.claimTask(agent.name);
        if (!task) {
          agent.status = "idle";
          await sleep(WAIT_MS);
          continue;
        }

        agent.status = "processing";
        const generated = generateMockBusinesses(task, agent.name);
        const validated = generated.filter((row) => row.name && row.city && row.category);

        for (const row of validated) {
          const { error } = await supabaseAdmin
            .from("businesses")
            .upsert(row, { onConflict: "name,city", ignoreDuplicates: false });

          if (error) {
            throw error;
          }
        }

        await supabaseAdmin
          .from("agent_tasks")
          .update({ status: "completed", assigned_agent: agent.name })
          .eq("id", task.id);

        agent.processedCount += 1;
        agent.status = "idle";
      } catch (error) {
        console.error(`Agent ${agent.name} failed`, error);
        agent.status = "error";
        agent.errors += 1;
        await sleep(WAIT_MS);
      }
    }
  }

  private async claimTask(agentName: string): Promise<AgentTask | null> {
    const { data, error } = await supabaseAdmin.rpc("claim_next_agent_task", {
      p_agent_name: agentName,
    });

    if (error) {
      throw error;
    }

    if (!data || data.length === 0) {
      return null;
    }

    return data[0] as AgentTask;
  }

  private async runManagerChecks() {
    const tenSecondsAgo = Date.now() - 10_000;

    this.agentStates.forEach((agent) => {
      if (new Date(agent.lastHeartbeat).getTime() < tenSecondsAgo && this.running) {
        console.warn(`Detected idle/frozen agent ${agent.name}; resetting to idle.`);
        agent.status = "idle";
      }
    });

    const { count: pendingTasks } = await supabaseAdmin
      .from("agent_tasks")
      .select("id", { count: "exact", head: true })
      .eq("status", "pending");

    if (!pendingTasks) {
      const seedTasks = ALLOWED_CATEGORIES.map((category) => ({
        task_type: "seed_collection",
        category,
        city: "baghdad",
        government_rate: "standard",
        status: "pending",
      }));
      await supabaseAdmin.from("agent_tasks").insert(seedTasks);
    }

    const { data: dupes } = await supabaseAdmin
      .from("businesses")
      .select("name, city")
      .limit(2000);

    if (dupes) {
      const set = new Set<string>();
      let duplicateCount = 0;
      dupes.forEach((d) => {
        const key = `${d.name}::${d.city}`;
        if (set.has(key)) {
          duplicateCount += 1;
        }
        set.add(key);
      });
      if (duplicateCount > 0) {
        console.warn(`Duplicate monitor: ${duplicateCount} duplicates seen in sampled rows.`);
      }
    }
  }
}
